name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 避免使用默认的 GITHUB_TOKEN
        fetch-depth: 0  # 获取完整的历史

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add upstream repository
      run: git remote add upstream https://github.com/fanmingming/live.git  # 替换为原仓库地址

    - name: Fetch upstream changes
      run: git fetch upstream  # 获取原仓库的最新代码

    - name: Rebase upstream changes
      run: git rebase upstream/main  # 使用 rebase 替代 merge，避免产生不必要的合并提交

    - name: Push changes to fork
      run: git push origin main --force-with-lease  # 强制推送更新到 fork
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 执行 push 操作
